### ISSUE TITLE
TTO Roadmap

### ISSUE THREAD

**Issue by ksimon1** [kubevirt/tekton-tasks-operator#35]
To improve usability of tekton tasks operator and kubevirt tekton tasks, we are planning to do these improvements:

- [ ] support  flavors in template tasks
- [ ] secrets and configmap parameters in disk virt sysprep
- [ ] checks which prevents user to create more TTO CRs
- [ ] TTO operator complient with crypto policy and cert rotation
- [ ] create-datavolume-from-manifest task written in Golang

**Comment by ksimon1** [comment]
Closing, as all items are finished
